resolver: lts-24.12

packages:
- .
- ../fractalstream-core
- ../../llvm-hs/llvm-hs
- ../../llvm-hs/llvm-hs-pure

extra-deps:

#- git: https://github.com/matt-noonan/llvm-hs.git
#  commit: 46fbe902a83a4198f296e2062c767b34ecc6be65
#  subdirs:
#    - llvm-hs
#    - llvm-hs-pure

- git: https://github.com/mgrabmueller/disassembler
  commit: 15a15db1fba50fd0ce52f26f43550fbad5529bf8

allow-newer: true

# Override default flag values for local packages and extra-deps
flags:
  llvm-hs:
    shared-llvm: true

ghc-options:
  llvm-hs:
    -optcxx=-std=c++17
