resolver: lts-24.12

packages:
- .
- ../fractalstream-core

extra-deps:

- git: https://github.com/matt-noonan/llvm-hs.git
  commit: 46fbe902a83a4198f296e2062c767b34ecc6be65
  subdirs:
    - llvm-hs
    - llvm-hs-pure


flags:
  llvm-hs:
    shared-llvm: false

ghc-options:
  llvm-hs:
    -optcxx=-std=c++17

allow-newer: true
